name: Create Release for Cloud Deploy

on:
  push:
    branches:
      - dev

jobs:
  files-changed:
    uses: ./.github/workflows/files-changed.yaml
    permissions:
      contents: read
      pull-requests: read

  create-release:
    runs-on: ubuntu-latest
    needs: files-changed
    if: needs.files-changed.outputs.app == 'true'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set variables
        id: vars
        run: |-
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "app_version=$(date +%Y%m%d)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v3"
        with:
          create_credentials_file: true
          project_id: ${{ secrets.PIPELINE_PROJECT_ID }}
          workload_identity_provider: "projects/${{ secrets.WIF_PROJECT_NUM }}/locations/global/workloadIdentityPools/${{ secrets.WIF_POOL_ID }}/providers/${{ secrets.WIF_PROVIDER_ID }}"
          service_account: "releaser@${{ secrets.PIPELINE_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: "latest"

      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      - name: "Build with Skaffold"
        working-directory: ./deploy
        env:
          APP_VERSION: ${{ steps.vars.outputs.app_version }}
        run: |-
          skaffold build \
            --filename skaffold.yaml \
            --default-repo "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.PIPELINE_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}" \
            --file-output artifacts.json

      - name: "Create Cloud Deploy Release and Trigger Initial Rollout"
        working-directory: ./deploy
        run: |-
          gcloud deploy releases create "release-${{ steps.vars.outputs.sha_short }}" \
            --region="${{ secrets.GCP_REGION }}" \
            --delivery-pipeline="app-pipeline" \
            --gcs-source-staging-dir="gs://${{ secrets.PIPELINE_PROJECT_ID }}-storage/app/source" \
            --build-artifacts=artifacts.json \
            --skaffold-file=skaffold.yaml \
            --enable-initial-rollout

      - name: "Result"
        run: |-
          echo "Release created: release-${{ steps.vars.outputs.sha_short }}" > $GITHUB_STEP_SUMMARY
